/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appIndexRouteImport } from './routes/(app)/index/route'

// Create/Update Routes

const appIndexRouteRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof appIndexRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof appIndexRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)/': typeof appIndexRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(app)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appIndexRouteRoute: typeof appIndexRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRouteRoute: appIndexRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)/"
      ]
    },
    "/(app)/": {
      "filePath": "(app)/index/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
